const tenantId = OneLearnStorage.getTenantId();
const session = OneLearnStorage.read("session", null);
if (!session) location.replace(`./login.html?tenant=${encodeURIComponent(tenantId)}`);
const els = { loader: document.getElementById("pageLoader"), welcomeText: document.getElementById("welcomeText"), logoutBtn: document.getElementById("logoutBtn"), refreshBtn: document.getElementById("refreshBtn"), heroTitle: document.getElementById("heroTitle"), heroSubtitle: document.getElementById("heroSubtitle"), totalCount: document.getElementById("totalCount"), inProgressCount: document.getElementById("inProgressCount"), completedCount: document.getElementById("completedCount"), urgentCount: document.getElementById("urgentCount"), tabs: document.getElementById("filterTabs"), search: document.getElementById("searchInput"), grid: document.getElementById("courseGrid"), empty: document.getElementById("emptyState") };
let tenant = { displayName: "웅진 OneLearn", brand: { primaryColor: "#F47721", welcomeMessage: "추천 과정, 진행 중인 과정, 수료 완료 과정을 한 곳에서 확인하세요." } };
let learner = { userId: session.userId, name: "정호준", email: session.email };
let courses = [], activeFilter = "all", searchQuery = "";
const fallbackCourses = [{ courseId: "legal-001", title: "법정의무과정 테스트 과정", description: "영상 시청 기록, 배속 정책, 본인확인, 수료 조건을 모두 추적하는 테스트 과정입니다.", category: "법정의무과정", required: true, dueDate: "2026-06-30", estimatedMinutes: 45, completionPolicy: { requiredCourseProgressPercent: 95, requireAllChaptersCompleted: true }, chapters: [{ chapterId: "ch-001" }] }, { courseId: "skill-001", title: "AI 시대 스킬 트랜스포메이션", description: "AI 시대에 필요한 스킬 전환의 개념과 조직 학습 전략을 이해하는 과정입니다.", category: "스킬과정", required: true, dueDate: "2026-07-15", estimatedMinutes: 60, completionPolicy: { requiredCourseProgressPercent: 90, requireAllChaptersCompleted: true }, chapters: [{ chapterId: "ch-001" }] }];
function finishLoading(){setTimeout(()=>els.loader.classList.add("done"),520)}
function cleanText(value){return String(value||"").replaceAll("배정","추천").replaceAll("교육","과정")}
function getOverrides(){return OneLearnStorage.read("learnerOverrides",{})}
function progressKey(courseId){return `progress:${session.userId}:${courseId}`}
function loadProgress(courseId){return OneLearnStorage.read(progressKey(courseId),{})}
function formatDate(dateString){if(!dateString)return"마감 없음";const date=new Date(`${dateString}T00:00:00`);if(Number.isNaN(date.getTime()))return dateString;return new Intl.DateTimeFormat("ko-KR",{year:"numeric",month:"2-digit",day:"2-digit"}).format(date)}
function daysUntil(dateString){if(!dateString)return null;const today=new Date();const due=new Date(`${dateString}T23:59:59`);return Math.ceil((due.getTime()-today.getTime())/(1000*60*60*24))}
function dueText(dateString){const d=daysUntil(dateString);if(d===null)return"마감 없음";if(d>0)return`${d}일 남음`;if(d===0)return"오늘 마감";return`${Math.abs(d)}일 지남`}
function isUrgent(dateString){const d=daysUntil(dateString);return d!==null&&d>=0&&d<=7}
function calc(course){const saved=loadProgress(course.courseId);const chapters=course.chapters||[];if(!chapters.length)return{ratio:0,completedChapters:0,totalChapters:0,completed:false};let total=0,done=0;chapters.forEach(ch=>{const st=saved[ch.chapterId]||{};const dur=Number(st.duration||0);const max=Number(st.maxAllowedTime||0);const ratio=dur>0?Math.min(100,Math.max(0,max/dur*100)):0;total+=ratio;if(st.completed)done+=1});const ratio=total/chapters.length;const required=Number(course.completionPolicy?.requiredCourseProgressPercent||95);const requireAll=course.completionPolicy?.requireAllChaptersCompleted!==false;return{ratio,completedChapters:done,totalChapters:chapters.length,completed:ratio>=required&&(!requireAll||done===chapters.length)}}
function status(course){const p=calc(course);if(p.completed)return"completed";if(p.ratio>0)return"progress";return"incomplete"}
function icon(course){const cat=cleanText(course.category);if(cat.includes("법정"))return"⚖️";if(cat.includes("스킬"))return"🚀";if(cat.includes("보안"))return"🛡️";if(cat.includes("안전"))return"🦺";if(cat.includes("윤리"))return"🤝";return"📚"}
async function init(){try{try{tenant=await OneLearnStorage.fetchJson(`./data/tenants/${tenantId}/tenant.json`)}catch{}document.documentElement.style.setProperty("--brand",tenant.brand?.primaryColor||"#F47721");try{const learnerData=await OneLearnStorage.fetchJson(`./data/tenants/${tenantId}/learners.json`);const overrides=getOverrides();learner=(learnerData.learners||[]).map(item=>({...item,...(overrides[item.userId]||{})})).find(item=>item.userId===session.userId)||learner}catch{}if(!learner.termsAccepted||!learner.privacyAccepted){location.replace(`./consent.html?tenant=${encodeURIComponent(tenantId)}`);return}try{const assignmentData=await OneLearnStorage.fetchJson(`./data/tenants/${tenantId}/assignments.json`);const assignments=(assignmentData.assignments||[]).filter(item=>item.userId===learner.userId&&item.status!=="removed");const courseList=await OneLearnStorage.fetchJson(`./data/tenants/${tenantId}/courses.json`);const courseMetas=courseList.courses||[];courses=await Promise.all(assignments.map(async assignment=>{const meta=courseMetas.find(item=>item.courseId===assignment.courseId);if(!meta)return null;const detail=await OneLearnStorage.fetchJson(meta.courseFile);return{...meta,...detail,required:assignment.required??meta.required??detail.required??true,dueDate:assignment.dueDate||meta.dueDate||detail.dueDate,assignmentId:assignment.assignmentId,category:meta.category||detail.category||"과정",estimatedMinutes:meta.estimatedMinutes||detail.estimatedMinutes||0}}));courses=courses.filter(Boolean)}catch{courses=fallbackCourses}renderTenant();render()}catch(error){console.error(error);courses=fallbackCourses;renderTenant();render()}finally{finishLoading()}}
function renderTenant(){els.welcomeText.textContent=`${tenant.displayName||tenant.tenantName} · ${learner.name} 님 어서오세요!`;els.heroTitle.textContent=`${learner.name} 님에게 추천하는 과정`;els.heroSubtitle.textContent=cleanText(tenant.brand?.welcomeMessage||"추천 과정, 진행 중인 과정, 수료 완료 과정을 한 곳에서 확인하세요.")}
function render(){const enriched=courses.map(course=>{const progress=calc(course);const courseStatus=status(course);return{...course,progressData:progress,status:courseStatus,urgent:isUrgent(course.dueDate)}});els.totalCount.textContent=enriched.length;els.completedCount.textContent=enriched.filter(c=>c.status==="completed").length;els.inProgressCount.textContent=enriched.filter(c=>c.status==="progress").length;els.urgentCount.textContent=enriched.filter(c=>c.urgent&&c.status!=="completed").length;const filtered=enriched.filter(course=>{const text=cleanText(`${course.title} ${course.category} ${course.description||""}`).toLowerCase();if(searchQuery&&!text.includes(searchQuery.toLowerCase()))return false;if(activeFilter==="all")return true;if(activeFilter==="required")return!!course.required;if(activeFilter==="progress")return course.status==="progress";if(activeFilter==="incomplete")return course.status!=="completed";if(activeFilter==="completed")return course.status==="completed";if(activeFilter==="urgent")return course.urgent&&course.status!=="completed";return true});renderCourses(filtered)}
function renderCourses(list){els.grid.innerHTML="";if(!list.length){els.empty.classList.remove("hidden");return}els.empty.classList.add("hidden");list.forEach(course=>{const p=course.progressData;const ratio=Math.round(p.ratio);const statusText=course.status==="completed"?"수료 완료":course.status==="progress"?"진행 중":"미수료";const actionText=course.status==="completed"?"다시 보기":course.status==="progress"?"이어보기":"학습 시작";const url=`./player.html?tenant=${encodeURIComponent(tenantId)}&course=${encodeURIComponent(course.courseId)}`;const card=document.createElement("article");card.className="course-card";card.innerHTML=`<div class="course-icon">${icon(course)}</div><div class="course-meta">${course.required?`<span class="course-pill required">필수</span>`:`<span class="course-pill">선택</span>`}<span class="course-pill">${cleanText(course.category||"과정")}</span><span class="course-pill ${course.status==="completed"?"completed":""}">${statusText}</span>${course.urgent&&course.status!=="completed"?`<span class="course-pill urgent">마감 임박</span>`:""}</div><h2 class="course-title">${cleanText(course.title)}</h2><p class="course-desc">${cleanText(course.description||course.subtitle||"과정 설명이 없습니다.")}</p><div class="course-progress-block"><div class="course-progress-head"><span>전체 진행률</span><strong>${ratio}%</strong></div><div class="course-progress-track"><div class="course-progress-fill" style="width:${ratio}%"></div></div></div><div class="course-info-grid"><div class="course-info"><span>마감일</span><strong>${formatDate(course.dueDate)}</strong></div><div class="course-info"><span>남은 기간</span><strong>${dueText(course.dueDate)}</strong></div><div class="course-info"><span>완료 챕터</span><strong>${p.completedChapters}/${p.totalChapters}개</strong></div><div class="course-info"><span>예상 시간</span><strong>${course.estimatedMinutes||0}분</strong></div></div><div class="course-actions"><a class="course-action" href="${url}">${actionText}</a><a class="course-sub-action" href="${url}">상세 보기</a></div>`;els.grid.appendChild(card)})}
els.tabs.addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;activeFilter=button.dataset.filter;els.tabs.querySelectorAll("button").forEach(item=>item.classList.toggle("active",item===button));render()});els.search.addEventListener("input",()=>{searchQuery=els.search.value.trim();render()});els.refreshBtn.addEventListener("click",()=>location.reload());els.logoutBtn.addEventListener("click",()=>{OneLearnStorage.remove("session");location.href=`./login.html?tenant=${encodeURIComponent(tenantId)}`});init();
